"""Constants for W3G replay parsing."""

# Magic string identifying W3G replay files (28 bytes)
MAGIC_STRING = b"Warcraft III recorded game\x1a\x00"

# Header sizes
BASE_HEADER_SIZE = 0x30  # 48 bytes for base header
SUBHEADER_V0_SIZE = 0x10  # 16 bytes
SUBHEADER_V1_SIZE = 0x14  # 20 bytes
HEADER_V0_TOTAL = 0x40  # 64 bytes
HEADER_V1_TOTAL = 0x44  # 68 bytes

# Game identifiers (little-endian representation)
GAME_ID_CLASSIC = b"WAR3"  # Reign of Chaos / Classic
GAME_ID_TFT = b"W3XP"  # The Frozen Throne
GAME_ID_REFORGED = b"W3XP"  # Reforged uses same as TFT
GAME_ID_REFORGED_ALT = b"PX3W"  # Alternative Reforged identifier

# Flags
FLAG_SINGLE_PLAYER = 0x0000
FLAG_MULTIPLAYER = 0x8000

# Race flags
RACE_HUMAN = 0x01
RACE_ORC = 0x02
RACE_NIGHT_ELF = 0x04
RACE_UNDEAD = 0x08
RACE_RANDOM = 0x20
RACE_SELECTABLE = 0x40  # Fixed race

# Slot status
SLOT_EMPTY = 0x00
SLOT_CLOSED = 0x01
SLOT_USED = 0x02

# Observer team IDs
OBSERVER_TEAM_CLASSIC = 12
OBSERVER_TEAM_REFORGED = 24

# Version threshold for Reforged
REFORGED_VERSION_THRESHOLD = 29

# Block IDs
BLOCK_LEAVE_GAME = 0x17
BLOCK_FIRST_START = 0x1A
BLOCK_SECOND_START = 0x1B
BLOCK_THIRD_START = 0x1C
BLOCK_GAME_START = 0x19
BLOCK_TIMESLOT_OLD = 0x1E
BLOCK_TIMESLOT = 0x1F
BLOCK_CHAT = 0x20
BLOCK_CHECKSUM = 0x22
BLOCK_FORCED_END = 0x2F

# Record IDs
RECORD_HOST = 0x00
RECORD_ADDITIONAL_PLAYER = 0x16

# Action IDs
ACTION_PAUSE = 0x01
ACTION_RESUME = 0x02
ACTION_SET_SPEED = 0x03
ACTION_INC_SPEED = 0x04
ACTION_DEC_SPEED = 0x05
ACTION_SAVE_GAME = 0x06
ACTION_SAVE_FINISHED = 0x07
ACTION_ABILITY_NO_PARAMS = 0x10
ACTION_ABILITY_TARGET_POS = 0x11
ACTION_ABILITY_POS_OBJECT = 0x12
ACTION_ABILITY_DROP_ITEM = 0x13
ACTION_ABILITY_TWO_POS = 0x14
ACTION_CHANGE_SELECTION = 0x16
ACTION_ASSIGN_GROUP = 0x17
ACTION_SELECT_GROUP = 0x18
ACTION_SELECT_SUBGROUP = 0x19
ACTION_PRE_SUBSELECTION = 0x1A
ACTION_UNKNOWN_1B = 0x1B
ACTION_SELECT_GROUND_ITEM = 0x1C
ACTION_CANCEL_HERO_REVIVAL = 0x1D
ACTION_REMOVE_FROM_QUEUE = 0x1E
ACTION_ALLY_OPTIONS = 0x50
ACTION_TRANSFER_RESOURCES = 0x51
ACTION_TRIGGER_COMMAND = 0x60
ACTION_ESC_PRESSED = 0x61
ACTION_SCENARIO_TRIGGER = 0x62
ACTION_HERO_SKILL_MENU = 0x66
ACTION_BUILDING_MENU = 0x67
ACTION_MINIMAP_SIGNAL = 0x68
ACTION_CONTINUE_GAME_B = 0x69
ACTION_CONTINUE_GAME_A = 0x6A
ACTION_UNKNOWN_75 = 0x75

# Chat flags
CHAT_FLAG_STARTUP = 0x10
CHAT_FLAG_NORMAL = 0x20

# Chat modes
CHAT_MODE_ALL = 0x00
CHAT_MODE_ALLIES = 0x01
CHAT_MODE_OBSERVERS = 0x02
# 0x03+ = specific player

# Game speeds
SPEED_SLOW = 0
SPEED_NORMAL = 1
SPEED_FAST = 2

# Leave game reasons
LEAVE_REASON_REMOTE = 0x01
LEAVE_REASON_LOCAL = 0x0C
LEAVE_REASON_UNKNOWN = 0x0E

# Leave game results
RESULT_LEFT = 0x01
RESULT_LEFT_ALT = 0x07
RESULT_LOST = 0x08
RESULT_WON = 0x09
RESULT_DRAW = 0x0A
RESULT_OBSERVER_LEFT = 0x0B

# Action sizes (for parsing, version-dependent in some cases)
# These are minimum sizes; some actions are variable length
ACTION_SIZES: dict[int, int | None] = {
    ACTION_PAUSE: 1,
    ACTION_RESUME: 1,
    ACTION_SET_SPEED: 2,
    ACTION_INC_SPEED: 1,
    ACTION_DEC_SPEED: 1,
    ACTION_SAVE_GAME: None,  # Variable: null-terminated string
    ACTION_SAVE_FINISHED: 5,
    ACTION_ABILITY_NO_PARAMS: 15,  # 14 for pre-1.07
    ACTION_ABILITY_TARGET_POS: 22,  # 21 for pre-1.07
    ACTION_ABILITY_POS_OBJECT: 30,  # 29 for pre-1.07
    ACTION_ABILITY_DROP_ITEM: 38,  # 37 for pre-1.07
    ACTION_ABILITY_TWO_POS: 43,  # 42 for pre-1.07
    ACTION_CHANGE_SELECTION: None,  # Variable: 4 + n*8 bytes
    ACTION_ASSIGN_GROUP: None,  # Variable: 4 + n*8 bytes
    ACTION_SELECT_GROUP: 3,
    ACTION_SELECT_SUBGROUP: None,  # Variable, version-dependent
    ACTION_PRE_SUBSELECTION: 1,
    ACTION_UNKNOWN_1B: 10,
    ACTION_SELECT_GROUND_ITEM: 10,
    ACTION_CANCEL_HERO_REVIVAL: 9,
    ACTION_REMOVE_FROM_QUEUE: 6,
    ACTION_ALLY_OPTIONS: 6,
    ACTION_TRANSFER_RESOURCES: 10,
    ACTION_TRIGGER_COMMAND: None,  # Variable: null-terminated string
    ACTION_ESC_PRESSED: 1,
    ACTION_SCENARIO_TRIGGER: 13,
    ACTION_HERO_SKILL_MENU: 1,
    ACTION_BUILDING_MENU: 1,
    ACTION_MINIMAP_SIGNAL: 13,
    ACTION_CONTINUE_GAME_B: 17,
    ACTION_CONTINUE_GAME_A: 17,
    ACTION_UNKNOWN_75: 2,
}
